### ISSUE TITLE
ScanFilesUtil类的一个小问题

### ISSUE THREAD

**Issue by yuugu** [Dboy233/ScanFIlesUtil#2]
ScanFilesUtil类285行应该返回file
加上
checkCoroutineSize()
return@launch

**Comment by Dboy233** [comment]
好的我看看

**Comment by Dboy233** [comment]
是285行么？285行是checkCoroutineSize()方法的最后一行。

**Comment by yuugu** [comment]
刚看好像代码改过了，现在是248行和249行之间加上
' checkCoroutineSize()
        return@launch'
您验证一下呢
我之前用好像发现过这个问题

**Comment by Dboy233** [comment]
这个地方map函数还在循环遍历执行当中。不能在这里暂停return。暂停return了的话，这个文件夹中的文件，就只扫描到一个file就直接停止了。我把检测放在了map函数之后，就是等这个文件夹的所有文件全部遍历检查完成后，此进程就算完成工作，检查协程的个数，然后return

**Comment by yuugu** [comment]
原来如此，我自己改错了，抱歉，谢谢指点~

**Comment by Dboy233** [comment]
有问题多交流，也能获得经验。
