### ISSUE TITLE
扫描图片出现数组越界

### ISSUE THREAD

**Issue by LuXiaoQiang** [Dboy233/ScanFIlesUtil#3]
在demo上添加notScanHiddenFiles()和scanPictureFiles()过滤，在scanComplete完成后遍历twoFileList的file，打印出来，会出现数组越界，怀疑是多线程处理的问题，直接运行demo，然后做一下的代码变动就会出现，具体代码截图如下：
![image](https://user-images.githubusercontent.com/11421833/170919276-19be6820-04c1-46b4-846f-2061492d97da.png)

![image](https://user-images.githubusercontent.com/11421833/170919241-2e14c142-89fa-4189-88ed-5691b6929805.png)

**Comment by Dboy233** [comment]
有崩溃日志吗。 @LuXiaoQiang

**Comment by Dboy233** [comment]
我这边试了一下。没有出现这问题

**Comment by Dboy233** [comment]
已经解决了。是多线程回调导致的，列表出现了null数据。[提交(edf10c13a8465add99399392d8a569a5707b6fb6)](https://github.com/Dboy233/ScanFIlesUtil/commit/edf10c13a8465add99399392d8a569a5707b6fb6)
