### ISSUE TITLE
优化flow 调用链

### ISSUE THREAD

**Issue by ningning21** [Dboy233/ScanFIlesUtil#4]
//在主线程回调
        mJobFlowScan = GlobalScope.launch(Dispatchers.IO) {
            flow<File> {
                recursionScan(file, this)
                onComplete()
            }.onStart {
                mScanFileListener?.onBegin()
                mScanTime = System.currentTimeMillis()
            }.catch {
                mScanFileListener?.onError(ERROR_UNKNOW, Throwable("我也不知道发生了什么"))
            }.collect {
                mScanFileListener?.onFile(it)
            }
        }

**Comment by Dboy233** [comment]
拴Q,已修
